from Rag.componets.web_scraping import WebScraper
from Rag.componets.chunking import Chunking
from Rag.logger import logging
from Rag.exception import RagException
from Rag.constant import *

class Pipeline:

    def __init__(self):...

    def webscraper(self):...

    def chunking(self):...

    def embedding(self):...

    def vector_database_dumping(self):...

    def RAG(self):...
